opt/scopeserver/dataserver/modules/gserver/GServer.py
opt/scopeserver/utils/GeneSetEnrichment.py

Fix bug reading gene set when performing gene set enrichment.

---

opt/scopeserver/dataserver/modules/gserver/GServer.py
opt/scopeserver/utils/CellColorByFeatures.py
opt/scopeserver/utils/Loom.py
opt/scopeserver/utils/SearchSpace.py
src/components/common/FeatureSearchBox.jsx

Implement feature to be able to query metrics that are defined in MetaData global attribute (see [SCope loom data format](https://github.com/aertslab/SCope/wiki/Data-Format)).

125-metrics-queryable

---

bin/install.js

Implement check for correct python version

---

bin/install.js
index.js
opt/scopeserver/bindserver/server.js
package.json

This should fix the windows electron app.
@mase5 can you test on linux? Particularly `npm run electron` and the open loom folder button, I had to change that. Either the package updated, or it is a bit different on windows.

175 windows app fixes

---

README.md

Install both python and nodejs with miniconda and improve
installation instructions.

Install both python and nodejs with miniconda.

---

opt/setup.py
package.json
webpack.config.js

Move from webpack 3 -> 4
Fixes #197

Fix and update package versions

---

opt/scopeserver/__init__.py
opt/scopeserver/bindserver/XServer.py
opt/scopeserver/dataserver/modules/gserver/GServer.py
opt/scopeserver/dataserver/modules/pserver/PServer.py
opt/scopeserver/dataserver/utils/cell_color_by_features.py
opt/scopeserver/dataserver/utils/data_file_handler.py
opt/scopeserver/dataserver/utils/gene_set_enrichment.py
opt/scopeserver/dataserver/utils/loom.py
opt/scopeserver/dataserver/utils/loom_file_handler.py

Feature 205 improve logging

---

opt/scopeserver/dataserver/modules/gserver/GServer.py
opt/scopeserver/dataserver/modules/pserver/PServer.py

Signed-off-by: KrisDavie <kristofer.davie@kuleuven.vib.be>

Add check for not deleting files from ro sessions

---

src/components/common/ViewerSidebar.jsx

- Should be configured in loom in the future
Signed-off-by: KrisDavie <kristofer.davie@kuleuven.vib.be>

Allow motifs from aertslab v9

---

opt/scopeserver/dataserver/utils/cell_color_by_features.py

Fix overflow when vmax > min(vals)

---

.github/workflows/continuous-integration-server.yml
README.md
opt/poetry.lock

Removes dependency on the pre-packaged github action for poetry.

Speed up server CI

---

opt/scopeserver/dataserver/utils/loom.py

Caching is already built in with self.nUMI, implement speedup and broader search for correct values
Closes #319

Feature/319 cache n_umi

---

opt/scopeserver/dataserver/modules/gserver/GServer.py
opt/scopeserver/dataserver/utils/loom_file_handler.py

Fix caching of info from deleted files

---

opt/poetry.lock
opt/pyproject.toml
opt/scopeserver/dataserver/modules/gserver/GServer.py
opt/scopeserver/dataserver/utils/loom.py
opt/scopeserver/dataserver/utils/search_space.py

See https://github.com/aertslab/SCope/issues/333

Replace lru_cache with methodtools version

---

opt/scopeserver/dataserver/utils/loom.py

#336 should be merged before this

Implement lru cache for clustering meta

---

opt/scopeserver/dataserver/modules/gserver/GServer.py

Close each loom connection when closing server

---

src/components/common/ViewerSidebar.jsx

Enable sorting of annotation table

---

src/components/common/Metadata.jsx
src/components/common/UploadModal.jsx
src/css/features.css

Fix modal positions

---

opt/scopeserver/dataserver/utils/loom.py

Fix typo in function argument

---

.github/workflows/continuous-integration-server.yml
opt/scopeserver/dataserver/utils/loom.py

Catch error when gene not present from regulon

---

opt/scopeserver/dataserver/modules/gserver/GServer.py

Fix cell metadata

---

.github/workflows/continuous-integration-server.yml
opt/scopeserver/result.py
opt/test/test_result.py

Add a Result type and tests

---

.github/workflows/continuous-integration-server.yml
opt/.env
opt/scopeserver/database.py
opt/scopeserver/dataserver/modules/gserver/GServer.py
opt/scopeserver/dataserver/modules/gserver/s_pb2.py
opt/scopeserver/dataserver/modules/gserver/s_pb2.pyi
opt/scopeserver/dataserver/modules/gserver/s_pb2_grpc.py
opt/scopeserver/dataserver/utils/annotation.py
opt/scopeserver/dataserver/utils/cell_color_by_features.py
opt/scopeserver/dataserver/utils/data.py
opt/scopeserver/dataserver/utils/gene_set_enrichment.py
opt/scopeserver/dataserver/utils/labels.py
opt/scopeserver/dataserver/utils/loom.py
opt/test/test_config.py
opt/test/test_data.py
opt/test/test_scopeserver.py
src/components/AppSidebar.jsx
src/components/common/API.jsx
src/components/common/Viewer.jsx
src/components/common/ViewerSidebar.jsx
src/proto/s.proto

Colouring alone makes distinguishing clusters difficult. This adds (togglable) display labels to the Viewer. An API was added to fetch the required data (name, colour, location) from the backend. As part of this typing was also improved.
Closes #78

Adds basic Feature Label display to the viewer 

---

opt/scopeserver/dataserver/utils/search_space.py

Quick fix to prevent issues when upgrading.

Fix for replacing old SearchSpace objects

---

opt/scopeserver/dataserver/utils/loom.py

Resulted in mismatched indexes on compare tab causing cells to dissapear

Fix logic error

---

src/components/GProfiler/link.ts
src/components/GProfiler/model.ts
src/components/common/ViewerSidebar.jsx

Enable gProfiler on regulon targets

Enable gProfiler on regulon targets

---

opt/scopeserver/dataserver/modules/gserver/GServer.py
opt/scopeserver/dataserver/modules/gserver/s_pb2.py
opt/scopeserver/dataserver/modules/gserver/s_pb2.pyi
opt/scopeserver/dataserver/modules/gserver/s_pb2_grpc.py
src/components/App.jsx
src/components/common/ViewerSidebar.jsx
src/proto/s.proto

This adds onto the previous functionality of downloading a cluster loom file with allowing a more specific selection using the lasso tool

Enable downloading a loom file of a selection of cells

---

opt/scopeserver/dataserver/modules/gserver/GServer.py

Rewite subloom generation for 10x speedup

---

src/components/Search/Search.test.ts
src/components/Search/model.ts

Closes #431

---

client/src/components/pages/Compare.jsx

This function was doing some weird stuff!

Simplify the Compare page select all annotations function
